#!/bin/sh
#
pkgUpdates() {
  # updates=$(xbps-install -S -un | cut -d' ' -f2 | sort | uniq -c | xargs)
  updates=$(checkupdates 2>/dev/null | wc -l) # arch

  if [ -z "$updates" ]; then
    echo "0"
  else
    echo "$updates"
  fi
}


backlight() {
  printf "%.0f\n" $(light -G)
}

wifi() {
  case "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" in
  up) printf "" ;;
  down) printf "󰤭" ;;
  esac
}

weather() {
  CITY=$(curl -s ipinfo.io/city)
  COUNTRY=$(curl -s ipinfo.io/country)

  LOCATION="${CITY},${COUNTRY}"
  WEATHER_INFO=$(curl -s "wttr.in/${LOCATION}?format=%c+%t")
  echo "$WEATHER_INFO"
}

"$@"
