#!/bin/sh

# this is just an example!
# my autostart stuffs here

xbacklight -set 20 &
xrdb merge ~/.Xresources &
feh --bg-fill ~/Pictures/wall/wall.png &
xset r rate 200 50 &

# run bar script and dwm ( never remove this )
bash ~/.config/chadwm/scripts/./bar.sh &
dwm

# you can paste the whole thing in .xinitrc to but at the end it should be ```exec dwm```
