#!/bin/sh

# this is just an example!
# add your autostart stuffs here
xbacklight -set 100 &
xmodmap ~/.xmodmap-sid &
xrdb merge ~/.Xresources &
feh --bg-fill ~/Pictures/wall/wallpaper.png &

# run bar script and dwm ( do not remove this )
bash ~/.config/chadwm/scripts/./bar.sh &
dwm
